---
name: cmpsc-100-fall-2021-project
break: true
indent: 4
---

docs/0_ideas.md:
    MatchFileFragment --fragment "TODO" --count 0 --exact --description "[IDEAS] No TODOs"

docs/1_progress.md:
    MatchFileFragment --fragment "TODO" --count 0 --exact --description "[PROGRESS REPORT] No TODOs"

docs/2_final-report.md:
    MatchFileFragment --fragment "TODO" --count 0 --exact --description "[FINAL REPORT] No TODOs"
    
ExecuteCommand --command "cd src && python main.py" --description "[PROJECT PROGRAM] Executes correctly"
